apiVersion: v1
kind: Secret
metadata:
  name: ci-gateway-db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "compose-postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ci_gateway_db:5432/compose-postgres"
  SPRING_DATASOURCE_USERNAME: "compose-postgres"