apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    bot-service: ci-gateway-db-pgdata
  name: ci-gateway-db-pgdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}
